server:
  port: #{server.port}
  
management:
  endpoint:
    health:
      enabled: #{management.endpoint.health.enabled}
  endpoints:
    web:
      base-path: #{management.endpoints.web.base-path}
  
dummyjson:
  server:
    url: #{dummyjson.server.url}